### ISSUE TITLE
Map doesn't scroll

### ISSUE THREAD

**Issue by cmlaird** [flighttactics/TAKTracker#1]
Map is fixed on user location and doesn't scroll or zoom. 

![Video of issue](https://github-production-user-asset-6210df.s3.amazonaws.com/34624443/257811836-4da8f47f-7d23-4c68-872e-3780d4240532.MOV)

**Comment by CoryFoy** [comment]
We'll likely do this similar to the other platforms where we have an icon that allows you to stay locked on your position or move freely around the map.

**Comment by CoryFoy** [comment]
Fixed in the latest TestFlight build. Moved from the SwiftUI `Map` back to `MKMap` which allows for more configuration options. iOS 17 offers some additional options as well with SwiftUI's Map but we want to keep this supporting iOS 15+ for now.

The latest build modifies the map to follow you with heading changes, but you can then pan and zoom the map around which disables auto-follow. Tapping on the map restores following the user. This will likely change in future releases to have an actual overlay to toggle locking on the user position.
