### ISSUE TITLE
Emergency Beacon Support

### ISSUE THREAD

**Issue by CoryFoy** [flighttactics/TAKTracker#11]
**Is your feature request related to a problem? Please describe.**
If a user has an issue while in the field they need a way to alert other users and command of their emergency

**Describe the solution you'd like**
We already have the screen for emergency alerts - we need to continue the implementation of this and ensure the correct messages are being sent for emergency beacon alerts

**Comment by jesustak** [comment]
Hi!!! can I activate the emergency beacon alerts by an external bluethooth device? it would be interested because i can be in a emergency situation where i need activate the alerts and i can't to open the movil and i can't activate de alerts because i am running or similar.... thank you very much and best regards!

**Comment by CoryFoy** [comment]
@jesustak Thanks for the comment! We're actually working on something like this for a private label client that will likely make its way back into TAK Tracker. I went ahead and opened a [feature request](https://github.com/flighttactics/TAKTracker/issues/49) for it.
